### ISSUE TITLE
More error reporting

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#11]
Tried to configure the virtualcurrency upstream to use https (setting port 443), which apparently doesn't work. (issue about https support coming next). Http works fine.

The issue here: upstream requests seems to fail silently, there's no error showing any sign of failure on the server console. Will make hard to debug anything if user reports that the admin interface doesn't load the items.

Could you look into that?

**Comment by elmigranto** [comment]
Added more logging. Client-side errors are not shown since `// Utils.registerAjaxErrorHandlers();` is commented out in `app.js`, I guess more particular error-reporting is required anyways.

Will add `.fetch` error handler for items collection in client-side as well. Maybe look for the way to better generalize it when we need to display more backbone collections later.
