### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#2]
This repo is a little messy... Would benefit for some cleanup.

Disable all features but the "Items" list.

**Comment by elmigranto** [comment]
What's up with tokens inside `utils.js`?

Is this login thing (like OAuth)? Why isn't SessionID enough? 

Is this Anti-CSRF thing? If so, I'd suggest changing it on every request and storing it in session instead of special separate in-memory place).

**Comment by j3k0** [comment]
Hi, I didn't write most of this, so I don't have any better understanding of it than you. 

This token seems like an authentication token that's stored in the users' cookie. If env `ADMIN_TOKEN` is defined, the server can be restarted and the authentication token still be the same after restart (or works too if multiple instance of the service is running).

Of course, the better way would be to store this token in a database, and "consume" it properly each time but I guess it's fine as it is... This is just a pretty internal admin interface, it can work with a single hard-coded user login and trust `https` to prevent man-in-the-middle attacks... (or maybe I'm missing another potential security threat?)

**Comment by elmigranto** [comment]
> Disable all features but the "Items" list.

Do you mean simply hide everything unrelated to items from UI or drop/remove things completely and bring them back later when required?

Unless these parts do work and you want them hidden for other reasons, I'd rather stash them away somewhere so we can bring them back later, and stick with react for views when implementing #3 (similarly to parcolab situation, with backbone doing lifting on models, collections, and other talk-to-server business). Maybe switch to browserify instead of requirejs as well.

**Comment by j3k0** [comment]
Stash away. Alright for react.
