### ISSUE TITLE
Data UI

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-admin#32]
Some improvements for the "Data" user interface

 - [x] Add a confirmation dialog before deleting.
 - [x] Refresh the list of documents when one is deleted.
 - [x] Limit number of documents listed (we expect them to be in the range of a few hundreds)
 - [x] Show the existing document IDs on a single line (spanned horizontally, not vertically), with "text-overflow: ellipsis" or something like that.

**Comment by elmigranto** [comment]
I limited number of documents shown to about ~10, it is scrollable, though:
![screenshot 2016-11-20 14 32 17](https://cloud.githubusercontent.com/assets/886388/20461900/92aacb72-af2e-11e6-81fc-42e7f11e8171.png)
Actually searching for less (redis' `SCAN` instead of `KEYS` or similar) isn't really worth it with just hundreds of keys, I don't think.

**Comment by elmigranto** [comment]
I prettied up form a bit, but don't like it too much anyways — feels a bit "jumpy" 🤔

Leaving it for later, though, should be functional enough, unless you want something changed.
